### ISSUE TITLE
Pie Control in Marshmallow 6.0

### ISSUE THREAD

**Issue by anildzs** [CyanPop/CyanPOP-Tools#1]
My current build is cyanpop_peregrine-MM_6.0.1-5.0-NIGHTLY-20160112 on Moto g XT1045. Functionality is beautiful so far. Just two questions:
1) I have enabled Pie Control and it works fine. However I cannot remove the details that show up above Pie Control - for Time, date, Carrier name etc even on selecting Bare option for Pie Style.

2) Even on expanded desktop and Pie Control enabled, bottom navigation buttons shows up frequently.

**Comment by Rolando-D** [comment]
And xda? what's the sense here... report ur problem on xda at peregrine thread or drop a PM to me.

**Comment by anildzs** [comment]
Hi RolanDroid - Your work is great for community. Just wanted to understand the following:1) Turn off details above the Pie buttons. Choosing Bare option in Pie control settings still displays the details such as clock, Carrier, Wifi etc.2) Navigation button still pops up occassionally even when Pie control is enabled and expanded desktop.
